version: '3.5'

services:
  apollo:
    image: foxiswho/docker-apollo:latest
    container_name: apollo
    hostname: apollo
    volumes:
    - ./data:/opt
    ports:
    - "8070:8070"
    - "8080:8080"
    - "8090:8090"
    - "8081:8081"
    - "8091:8091"
    - "8082:8082"
    - "8092:8092"
    - "8083:8083"
    - "8093:8093"
    #restart: always
# 启动前,确认对应环境的数据库已经建立，否则apollo无法启动.
# 默认端口:portal:8070; dev:8080,8090; fat:8081,8091; uat:8082,8092; pro:8083,8093
    environment:
      PORTAL_DB: jdbc:mysql://10.0.0.8:3306/ApolloPortalDB?characterEncoding=utf8
      PORTAL_DB_USER: root
      PORTAL_DB_PWD: root
#      PORTAL_PORT: 80

      DEV_DB: jdbc:mysql://10.0.0.8:3306/ApolloConfigDBDev?characterEncoding=utf8
      DEV_DB_USER: root
      DEV_DB_PWD: root
      
#      FAT_DB: jdbc:mysql://10.0.0.8:3306/ApolloConfigDBFat?characterEncoding=utf8
#      FAT_DB_USER: root
#      FAT_DB_PWD: root
#
#      #UAT_DB: jdbc:mysql://10.0.0.8:3306/ApolloConfigDBUat?characterEncoding=utf8
#      UAT_DB_USER: root
#      UAT_DB_PWD: root
#
#      #PRO_DB: jdbc:mysql://10.0.0.8:3306/ApolloConfigDBPro?characterEncoding=utf8
#      PRO_DB_USER: root
#      PRO_DB_PWD: root
  mysql:
    image: mariadb:latest
    hostname: mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - /tmp/:/tmp/